version: '3.1'
services:

  stats-server:
    build: ./stats/stats
    image: stats-server-image
    container_name: stats
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:postgresql://stats-db:5432/explore_with_me_database
      - spring.datasource.username=root
      - spring.datasource.password=root

  stats-db:
    build: ./stats/stats-db
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main/main
    image: main-image
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    build: ./main/main
    container_name: main-db-container
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root